[deploy]
bucket = 'cfn-artifacts-beici'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://beici-demo.xyz'
EnvBackendUrl = 'https://api.beici-demo.xyz'
DDBMessageTable = 'CrdDdb-DynamoDBTable-OY28TEYFKEV3'